swagger: "2.0"
info:
  title: Restaurant Order API
  description: API for creating orders and retrieving bills
  version: "1.0.0"
host: example.com
basePath: /
schemes:
  - http
paths:
  /api/order:
    post:
      summary: Create a new order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: order
          in: body
          description: Order details
          required: true
          schema:
            type: object
            properties:
              table_number:
                type: integer
              items:
                type: array
                items:
                  type: object
                  properties:
                    product_name:
                      type: string
                    quantity:
                      type: integer
      responses:
        201:
          description: Order created successfully
        400:
          description: Invalid request payload
  /api/bill/{table_number}:
    get:
      summary: Get bill for a specific table
      parameters:
        - name: table_number
          in: path
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: Bill retrieved successfully
          schema:
            type: object
            properties:
              orders:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    table_number:
                      type: integer
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product:
                            type: object
                            properties:
                              name:
                                type: string
                          quantity:
                            type: integer
              total_amount:
                type: number
                format: float
        500:
          description: Failed to retrieve orders
